% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL
% Created Thu Jul 12 16:50:20 IRDT 2012
%
% This script assumes these variables are defined:
%
%   simpleclusterInputs - input data.

load sweet_bitter;

inputs = X';

% Create a Self-Organizing Map
LatticeSize=[10 10];
net = selforgmap(LatticeSize);
net.TrainParam.Epochs=200;

% Train the Network
[net tr] = train(net,inputs);

% Test the Network
outputs = net(inputs);

% View the Network
%view(net)

% Plots
% Uncomment these lines to enable various plots.
figure;
plotsomtop(net)
set(gcf,'Toolbar','figure');

% figure;
% plotsomnc(net);
% set(gcf,'Toolbar','figure');
% 
% figure;
% plotsomnd(net);
% set(gcf,'Toolbar','figure');
% 
% figure;
% plotsomplanes(net);
% set(gcf,'Toolbar','figure');
% 
% figure;
% plotsomhits(net,inputs);
% set(gcf,'Toolbar','figure');

figure;
plotsompos(net,inputs);
set(gcf,'Toolbar','figure');
